package gg.revival.rac.modules;

public enum Cheat {

    PHASE, REACH, FLIGHT, AURA_A, AURA_B, AUTOCLICKER, SPEED, VCLIP, STEP, JESUS, FASTBLOCK, REGEN, FASTBOW, NOSWING, BEDLEAVE, SPIDER, NOFALL, BADPACKETS, GLIDE, ASCENSION

}
